kotlin.code.style=official

# Gradle caching args, etc
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.entries-per-key=3
org.gradle.kotlin.dsl.allWarningsAsErrors=true
